### ISSUE TITLE
Dead link `HKLM Run and RunOnce registry keys`

### ISSUE THREAD

**Issue by Qualadore** [persistence-info/persistence-info.github.io#5]
Page https://persistence-info.github.io/Data/run.html has a dead link
`- [HKLM Run and RunOnce registry keys](hklmrun.html)`

**Comment by gtworek** [comment]
Thanks! Will fix it soon.

--
G.
________________________________
From: Qualadore ***@***.***>
Sent: Friday, August 19, 2022 6:50:09 AM
To: persistence-info/persistence-info.github.io ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [persistence-info/persistence-info.github.io] Dead link `HKLM Run and RunOnce registry keys` (Issue #5)


Page https://persistence-info.github.io/Data/run.html has a dead link
- [HKLM RunandRunOnce registry keys](hklmrun.html)

**Comment by gtworek** [comment]
Done. Thank you again.
